#!/usr/bin/env python
import RPi.GPIO as GPIO
from time import sleep

# set GPIO to to mode BCM to get nice
# numbers for GPIO ports
GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)

# relay is attached to GPIO PIN #18
GPIO.setup(18, GPIO.OUT)

# turn relay on for 10 seconds
GPIO.output(18, GPIO.HIGH)
sleep(4)
GPIO.output(18, GPIO.LOW)
